# Start development building containers(db, etc): docker-compose up -d --build
# Stop development: docker-compose stop
# Start development (keeping db): docker-compose start
# Remove all volumes: docker-compose down --volumes
# Redis is deactivated at the moment.
version: '3.9'
services:
  api-notemates:
    container_name: api-notemates
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - BUILD_STAGE=${BUILD_STAGE}
      target: ${BUILD_STAGE}
    env_file:
        - .env
    environment:
      - BUILD_STAGE=${BUILD_STAGE}    
    volumes:
      - .:/usr/src/app
    # Run in dev Mode: npm run start:dev
    # Run in prod Mode: node dist/main.js
    command: sh -c "if [ '$BUILD_STAGE' = 'development' ]; then npm run start:debug; else node dist/main.js; fi"
    ports:
      - ${APP_PORT}:3000 # 3001:3000
      - "9229:9229"    # Debugging port
    depends_on:
      #- redis
      - postgres-notemates
  #redis: # Name of container
    #image: redis
    #ports:
      #- 6379:6379
    #volumes: 
      #- redis:/data
  postgres-notemates:
    container_name: postgres-notemates
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports: 
      - ${DATABASE_PORT}:5432 # 5434:5432
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data

volumes:
  docker-nest-postgres:
  #redis:
    #driver: local
